DJANGO/projects/quick_start/enquetes/urls.py
from django.urls import path

from . import views

app_name = 'enquetes'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pergunta_id>/', views.detalhe, name='detalhe'),
    path('<int:pergunta_id>/resultado', views.resultado, name='resultado'),
    path('<int:question_id>/voto', views.voto, name='voto'),
]

DJANGO/projects/quick_start/quick_start/urls.py
from django.contrib import admin
from django.urls import include, path


# O Include permite fazer refenrecia a outros urlsConf
urlpatterns = [
    path('enquetes/', include('enquetes.urls')),
    path('admin/', admin.site.urls),
]

DJANGO/projects/quick_start/enquetes/models.py
from datetime import datetime

from django.db import models
from django.utils import timezone

class Pergunta(models.Model):
    
    texto_pergunta = models.CharField(max_length=200)
    data_pub = models.DateTimeField('data de publicacao')
    
    def was_published_recently(self):
        return self.data_pub >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.texto_pergunta




class Voto(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto_voto = models.CharField(max_length=200)
    avaliacao = models.IntegerField(default=0)

    def __str__(self):
        return self.texto_voto

DJANGO/projects/quick_start/enquetes/views.py
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Pergunta, Voto

def index(request):
    latest_question_list = Pergunta.objects.order_by('data_pub')[:5]
    #template = loader.get_template('enquetes/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    #return HttpResponse(template.render(context, request))
    return render(request, 'enquetes/index.html', context)


def detalhe(request, pergunta_id):
    #try:
    #    pergunta = Pergunta.objects.get(pk=pergunta_id)
    #except Pergunta.DoesNotExist:
    #    raise Http404("Pergunta não existe")
    #return render(request, 'enquetes/detalhe.html', {'question': pergunta})
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'enquetes/detalhe.html', {'question': pergunta})

def resultado(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    return render(request, 'enquetes/resultado.html', {'question': pergunta})

def voto(request, question_id): 
    question = get_object_or_404(Pergunta, pk=question_id)
    try:
        selected_choice = question.voto_set.get(pk=request.POST['voto'])
        
    except (KeyError, Voto.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'enquetes/detalhe.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.avaliacao += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('enquetes:resultado', args=(question.id,)))
    

DJANGO/projects/quick_start/enquetes/templates/enquetes/detalhe.html
<form action="{% url 'enquetes:voto' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for voto in question.voto_set.all %}
            <input type="radio" name="voto" id="voto{{ forloop.counter }}" value="{{ voto.id }}">
            <label for="voto{{ forloop.counter }}">{{ voto.texto_voto }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>

DJANGO/projects/quick_start/enquetes/templates/enquetes/index.html
{% if latest_question_list %}
    <ul>
    {% for pergunta in latest_question_list %}
        <!--So é possivel usar a tag url porque foi definido um name nas configuraçõs de url do app-->
        <li><a href="{% url 'enquetes:detalhe' pergunta.id %}">{{ pergunta.texto_pergunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

DJANGO/projects/quick_start/enquetes/templates/enquetes/resultado.html
<h1>{{ question.texto_pergunta }}</h1>

<ul>
{% for voto in question.voto_set.all %}
    <li>{{ voto.texto_voto }} -- {{ voto.avaliacao }} votos{{ voto.avaliacao|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'enquetes:detalhe' question.id %}">votar novamente?</a>